assigness: []
harvest_options:
  goldcopy: false
  path: s3://ooi-data
  refresh: true
  test: false
instrument: RS01SBPS-SF01A-4F-PCO2WA101
stream:
  method: streamed
  name: pco2w_a_thermistor_voltage
workflow_config:
  schedule: 0 0 * * *
